languageCode = "pt-pt"
languageName = "Português (Portugal)"
weight = 5
title = "Home"

[params]
  displayName = "Português (Portugal)"
  isoCode = "pt-pt"
  rtl = false
  dateFormat = "2 de January de 2006"
  logo = ""
  description = "AI sloppers"

[params.author]
  name = "Kaw0ru"
  image = "img/kaw0ruprofilepicture.jpg"
  headline = "AI sloppers"
  bio = "AI sloppers"
  links = []
